language: node_js
node_js:
  - "13.9.0"
env:
  global:
    - COVERALLS_PARALLEL=true
install:
  - npm i
  - npm i -g codecov
  - npm i -g coveralls
script:
  - npm run install:fixtures
  - npm run test:coverage && codecov
after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
cache:
  directories:
    - node_modules